### ISSUE TITLE
Include `.jl` as source document type, or make this configurable

### ISSUE THREAD

**Issue by davidavdav** [ojsheikh/unicode-latex#12]
Hello, 

I see that the `.ts` code is generated from julia, and the reason I use this extension is to use it for editing `.jl` files.  Any chance that julia source files are included in the set of file types for which this extension is activated?

**Comment by danlub** [comment]
I think this should be configurable. This extension is useful for python and julia users, for example

**Comment by davidavdav** [comment]
Configurable or not, I'd love to see it implemented.  I'd do it myself if I knew how.

**Comment by matklad** [comment]
I think julia extension provides this feature for julia out of the box? 

However, I'd totally would love to use this for `.adoc` files :)
